package com.csq.entity;

public class Classes {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column class_tb.id
	 * @mbg.generated  Mon Apr 22 23:31:21 CST 2019
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column class_tb.apply_name
	 * @mbg.generated  Mon Apr 22 23:31:21 CST 2019
	 */
	private String applyName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column class_tb.apply_number
	 * @mbg.generated  Mon Apr 22 23:31:21 CST 2019
	 */
	private String applyStudentNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column class_tb.apply_collage
	 * @mbg.generated  Mon Apr 22 23:31:21 CST 2019
	 */
	private String applyCollage;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column class_tb.apply_class
	 * @mbg.generated  Mon Apr 22 23:31:21 CST 2019
	 */
	private String applyClass;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column class_tb.apply_course
	 * @mbg.generated  Mon Apr 22 23:31:21 CST 2019
	 */
	private String applyCourse;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column class_tb.apply_classroom
	 * @mbg.generated  Mon Apr 22 23:31:21 CST 2019
	 */
	private String applyClassroom;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column class_tb.apply_time
	 * @mbg.generated  Mon Apr 22 23:31:21 CST 2019
	 */
	private String applyTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column class_tb.apply_state
	 * @mbg.generated  Mon Apr 22 23:31:21 CST 2019
	 */
	private int applyState;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column class_tb.remarks
	 * @mbg.generated  Mon Apr 22 23:31:21 CST 2019
	 */
	private String remarks;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column class_tb.id
	 * @return  the value of class_tb.id
	 * @mbg.generated  Mon Apr 22 23:31:21 CST 2019
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column class_tb.id
	 * @param id  the value for class_tb.id
	 * @mbg.generated  Mon Apr 22 23:31:21 CST 2019
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column class_tb.apply_name
	 * @return  the value of class_tb.apply_name
	 * @mbg.generated  Mon Apr 22 23:31:21 CST 2019
	 */
	public String getApplyName() {
		return applyName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column class_tb.apply_name
	 * @param applyName  the value for class_tb.apply_name
	 * @mbg.generated  Mon Apr 22 23:31:21 CST 2019
	 */
	public void setApplyName(String applyName) {
		this.applyName = applyName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column class_tb.apply_number
	 * @return  the value of class_tb.apply_number
	 * @mbg.generated  Mon Apr 22 23:31:21 CST 2019
	 */
	public String getApplyStudentNumber() {
		return applyStudentNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column class_tb.apply_number
	 * @param applyNumber  the value for class_tb.apply_number
	 * @mbg.generated  Mon Apr 22 23:31:21 CST 2019
	 */
	public void setApplyStudentNumber(String applyStudentNumber) {
		this.applyStudentNumber = applyStudentNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column class_tb.apply_collage
	 * @return  the value of class_tb.apply_collage
	 * @mbg.generated  Mon Apr 22 23:31:21 CST 2019
	 */
	public String getApplyCollage() {
		return applyCollage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column class_tb.apply_collage
	 * @param applyCollage  the value for class_tb.apply_collage
	 * @mbg.generated  Mon Apr 22 23:31:21 CST 2019
	 */
	public void setApplyCollage(String applyCollage) {
		this.applyCollage = applyCollage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column class_tb.apply_class
	 * @return  the value of class_tb.apply_class
	 * @mbg.generated  Mon Apr 22 23:31:21 CST 2019
	 */
	public String getApplyClass() {
		return applyClass;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column class_tb.apply_class
	 * @param applyClass  the value for class_tb.apply_class
	 * @mbg.generated  Mon Apr 22 23:31:21 CST 2019
	 */
	public void setApplyClass(String applyClass) {
		this.applyClass = applyClass;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column class_tb.apply_course
	 * @return  the value of class_tb.apply_course
	 * @mbg.generated  Mon Apr 22 23:31:21 CST 2019
	 */
	public String getApplyCourse() {
		return applyCourse;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column class_tb.apply_course
	 * @param applyCourse  the value for class_tb.apply_course
	 * @mbg.generated  Mon Apr 22 23:31:21 CST 2019
	 */
	public void setApplyCourse(String applyCourse) {
		this.applyCourse = applyCourse;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column class_tb.apply_classroom
	 * @return  the value of class_tb.apply_classroom
	 * @mbg.generated  Mon Apr 22 23:31:21 CST 2019
	 */
	public String getApplyClassroom() {
		return applyClassroom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column class_tb.apply_classroom
	 * @param applyClassroom  the value for class_tb.apply_classroom
	 * @mbg.generated  Mon Apr 22 23:31:21 CST 2019
	 */
	public void setApplyClassroom(String applyClassroom) {
		this.applyClassroom = applyClassroom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column class_tb.apply_time
	 * @return  the value of class_tb.apply_time
	 * @mbg.generated  Mon Apr 22 23:31:21 CST 2019
	 */
	public String getApplyTime() {
		return applyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column class_tb.apply_time
	 * @param applyTime  the value for class_tb.apply_time
	 * @mbg.generated  Mon Apr 22 23:31:21 CST 2019
	 */
	public void setApplyTime(String applyTime) {
		this.applyTime = applyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column class_tb.apply_state
	 * @return  the value of class_tb.apply_state
	 * @mbg.generated  Mon Apr 22 23:31:21 CST 2019
	 */
	public int getApplyState() {
		return applyState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column class_tb.apply_state
	 * @param applyState  the value for class_tb.apply_state
	 * @mbg.generated  Mon Apr 22 23:31:21 CST 2019
	 */
	public void setApplyState(int applyState) {
		this.applyState = applyState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column class_tb.remarks
	 * @return  the value of class_tb.remarks
	 * @mbg.generated  Mon Apr 22 23:31:21 CST 2019
	 */
	public String getRemarks() {
		return remarks;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column class_tb.remarks
	 * @param remarks  the value for class_tb.remarks
	 * @mbg.generated  Mon Apr 22 23:31:21 CST 2019
	 */
	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}
}