package com.csq.entity;

public class Complain {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complain_tb.id
     *
     * @mbg.generated Wed Apr 24 10:39:06 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complain_tb.complain_man
     *
     * @mbg.generated Wed Apr 24 10:39:06 CST 2019
     */
    private String complainMan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complain_tb.complain_reason
     *
     * @mbg.generated Wed Apr 24 10:39:06 CST 2019
     */
    private String complainReason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complain_tb.complain_company
     *
     * @mbg.generated Wed Apr 24 10:39:06 CST 2019
     */
    private String complainCompany;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complain_tb.complain_type
     *
     * @mbg.generated Wed Apr 24 10:39:06 CST 2019
     */
    private String complainType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complain_tb.complain_time
     *
     * @mbg.generated Wed Apr 24 10:39:06 CST 2019
     */
    private String complainTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complain_tb.remark
     *
     * @mbg.generated Wed Apr 24 10:39:06 CST 2019
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complain_tb.id
     *
     * @return the value of complain_tb.id
     *
     * @mbg.generated Wed Apr 24 10:39:06 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complain_tb.id
     *
     * @param id the value for complain_tb.id
     *
     * @mbg.generated Wed Apr 24 10:39:06 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complain_tb.complain_man
     *
     * @return the value of complain_tb.complain_man
     *
     * @mbg.generated Wed Apr 24 10:39:06 CST 2019
     */
    public String getComplainMan() {
        return complainMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complain_tb.complain_man
     *
     * @param complainMan the value for complain_tb.complain_man
     *
     * @mbg.generated Wed Apr 24 10:39:06 CST 2019
     */
    public void setComplainMan(String complainMan) {
        this.complainMan = complainMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complain_tb.complain_reason
     *
     * @return the value of complain_tb.complain_reason
     *
     * @mbg.generated Wed Apr 24 10:39:06 CST 2019
     */
    public String getComplainReason() {
        return complainReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complain_tb.complain_reason
     *
     * @param complainReason the value for complain_tb.complain_reason
     *
     * @mbg.generated Wed Apr 24 10:39:06 CST 2019
     */
    public void setComplainReason(String complainReason) {
        this.complainReason = complainReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complain_tb.complain_company
     *
     * @return the value of complain_tb.complain_company
     *
     * @mbg.generated Wed Apr 24 10:39:06 CST 2019
     */
    public String getComplainCompany() {
        return complainCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complain_tb.complain_company
     *
     * @param complainCompany the value for complain_tb.complain_company
     *
     * @mbg.generated Wed Apr 24 10:39:06 CST 2019
     */
    public void setComplainCompany(String complainCompany) {
        this.complainCompany = complainCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complain_tb.complain_type
     *
     * @return the value of complain_tb.complain_type
     *
     * @mbg.generated Wed Apr 24 10:39:06 CST 2019
     */
    public String getComplainType() {
        return complainType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complain_tb.complain_type
     *
     * @param complainType the value for complain_tb.complain_type
     *
     * @mbg.generated Wed Apr 24 10:39:06 CST 2019
     */
    public void setComplainType(String complainType) {
        this.complainType = complainType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complain_tb.complain_time
     *
     * @return the value of complain_tb.complain_time
     *
     * @mbg.generated Wed Apr 24 10:39:06 CST 2019
     */
    public String getComplainTime() {
        return complainTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complain_tb.complain_time
     *
     * @param complainTime the value for complain_tb.complain_time
     *
     * @mbg.generated Wed Apr 24 10:39:06 CST 2019
     */
    public void setComplainTime(String complainTime) {
        this.complainTime = complainTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complain_tb.remark
     *
     * @return the value of complain_tb.remark
     *
     * @mbg.generated Wed Apr 24 10:39:06 CST 2019
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complain_tb.remark
     *
     * @param remark the value for complain_tb.remark
     *
     * @mbg.generated Wed Apr 24 10:39:06 CST 2019
     */
    public void setRemark(String remarks) {
        this.remarks = remarks;
    }
}