package com.csq.entity;

public class Idea {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column idea_tb.id
	 * @mbg.generated  Tue Apr 30 20:38:38 CST 2019
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column idea_tb.person
	 * @mbg.generated  Tue Apr 30 20:38:38 CST 2019
	 */
	private String person;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column idea_tb.time
	 * @mbg.generated  Tue Apr 30 20:38:38 CST 2019
	 */
	private String time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column idea_tb.title
	 * @mbg.generated  Tue Apr 30 20:38:38 CST 2019
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column idea_tb.content
	 * @mbg.generated  Tue Apr 30 20:38:38 CST 2019
	 */
	private String content;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column idea_tb.classes
	 * @mbg.generated  Tue Apr 30 20:38:38 CST 2019
	 */
	private String classes;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column idea_tb.collage
	 * @mbg.generated  Tue Apr 30 20:38:38 CST 2019
	 */
	private String collage;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column idea_tb.remark
	 * @mbg.generated  Tue Apr 30 20:38:38 CST 2019
	 */
	private String remarks;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column idea_tb.id
	 * @return  the value of idea_tb.id
	 * @mbg.generated  Tue Apr 30 20:38:38 CST 2019
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column idea_tb.id
	 * @param id  the value for idea_tb.id
	 * @mbg.generated  Tue Apr 30 20:38:38 CST 2019
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column idea_tb.person
	 * @return  the value of idea_tb.person
	 * @mbg.generated  Tue Apr 30 20:38:38 CST 2019
	 */
	public String getPerson() {
		return person;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column idea_tb.person
	 * @param person  the value for idea_tb.person
	 * @mbg.generated  Tue Apr 30 20:38:38 CST 2019
	 */
	public void setPerson(String person) {
		this.person = person;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column idea_tb.time
	 * @return  the value of idea_tb.time
	 * @mbg.generated  Tue Apr 30 20:38:38 CST 2019
	 */
	public String getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column idea_tb.time
	 * @param time  the value for idea_tb.time
	 * @mbg.generated  Tue Apr 30 20:38:38 CST 2019
	 */
	public void setTime(String time) {
		this.time = time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column idea_tb.title
	 * @return  the value of idea_tb.title
	 * @mbg.generated  Tue Apr 30 20:38:38 CST 2019
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column idea_tb.title
	 * @param title  the value for idea_tb.title
	 * @mbg.generated  Tue Apr 30 20:38:38 CST 2019
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column idea_tb.content
	 * @return  the value of idea_tb.content
	 * @mbg.generated  Tue Apr 30 20:38:38 CST 2019
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column idea_tb.content
	 * @param content  the value for idea_tb.content
	 * @mbg.generated  Tue Apr 30 20:38:38 CST 2019
	 */
	public void setContent(String content) {
		this.content = content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column idea_tb.classes
	 * @return  the value of idea_tb.classes
	 * @mbg.generated  Tue Apr 30 20:38:38 CST 2019
	 */
	public String getClasses() {
		return classes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column idea_tb.classes
	 * @param classes  the value for idea_tb.classes
	 * @mbg.generated  Tue Apr 30 20:38:38 CST 2019
	 */
	public void setClasses(String classes) {
		this.classes = classes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column idea_tb.collage
	 * @return  the value of idea_tb.collage
	 * @mbg.generated  Tue Apr 30 20:38:38 CST 2019
	 */
	public String getCollage() {
		return collage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column idea_tb.collage
	 * @param collage  the value for idea_tb.collage
	 * @mbg.generated  Tue Apr 30 20:38:38 CST 2019
	 */
	public void setCollage(String collage) {
		this.collage = collage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column idea_tb.remark
	 * @return  the value of idea_tb.remark
	 * @mbg.generated  Tue Apr 30 20:38:38 CST 2019
	 */
	public String getRemarks() {
		return remarks;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column idea_tb.remark
	 * @param remark  the value for idea_tb.remark
	 * @mbg.generated  Tue Apr 30 20:38:38 CST 2019
	 */
	public void setRemark(String remarks) {
		this.remarks = remarks;
	}
}