package com.csq.entity;

public class LoseFound {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lose_found_tb.id
     *
     * @mbg.generated Thu Apr 18 19:35:10 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lose_found_tb.lose_name
     *
     * @mbg.generated Thu Apr 18 19:35:10 CST 2019
     */
    private String loseName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lose_found_tb.lose_time
     *
     * @mbg.generated Thu Apr 18 19:35:10 CST 2019
     */
    private String loseTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lose_found_tb.lose_sj_man
     *
     * @mbg.generated Thu Apr 18 19:35:10 CST 2019
     */
    private String loseSjMan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lose_found_tb.lose_sj_phone
     *
     * @mbg.generated Thu Apr 18 19:35:10 CST 2019
     */
    private String loseSjPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lose_found_tb.lose_man
     *
     * @mbg.generated Thu Apr 18 19:35:10 CST 2019
     */
    private String loseMan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lose_found_tb.lose_phone
     *
     * @mbg.generated Thu Apr 18 19:35:10 CST 2019
     */
    private String losePhone;
    
    private int loseState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lose_found_tb.remarks
     *
     * @mbg.generated Thu Apr 18 19:35:10 CST 2019
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lose_found_tb.id
     *
     * @return the value of lose_found_tb.id
     *
     * @mbg.generated Thu Apr 18 19:35:10 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lose_found_tb.id
     *
     * @param id the value for lose_found_tb.id
     *
     * @mbg.generated Thu Apr 18 19:35:10 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lose_found_tb.lose_name
     *
     * @return the value of lose_found_tb.lose_name
     *
     * @mbg.generated Thu Apr 18 19:35:10 CST 2019
     */
    public String getLoseName() {
        return loseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lose_found_tb.lose_name
     *
     * @param loseName the value for lose_found_tb.lose_name
     *
     * @mbg.generated Thu Apr 18 19:35:10 CST 2019
     */
    public void setLoseName(String loseName) {
        this.loseName = loseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lose_found_tb.lose_time
     *
     * @return the value of lose_found_tb.lose_time
     *
     * @mbg.generated Thu Apr 18 19:35:10 CST 2019
     */
    public String getLoseTime() {
        return loseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lose_found_tb.lose_time
     *
     * @param loseTime the value for lose_found_tb.lose_time
     *
     * @mbg.generated Thu Apr 18 19:35:10 CST 2019
     */
    public void setLoseTime(String loseTime) {
        this.loseTime = loseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lose_found_tb.lose_sj_man
     *
     * @return the value of lose_found_tb.lose_sj_man
     *
     * @mbg.generated Thu Apr 18 19:35:10 CST 2019
     */
    public String getLoseSjMan() {
        return loseSjMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lose_found_tb.lose_sj_man
     *
     * @param loseSjMan the value for lose_found_tb.lose_sj_man
     *
     * @mbg.generated Thu Apr 18 19:35:10 CST 2019
     */
    public void setLoseSjMan(String loseSjMan) {
        this.loseSjMan = loseSjMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lose_found_tb.lose_sj_phone
     *
     * @return the value of lose_found_tb.lose_sj_phone
     *
     * @mbg.generated Thu Apr 18 19:35:10 CST 2019
     */
    public String getLoseSjPhone() {
        return loseSjPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lose_found_tb.lose_sj_phone
     *
     * @param loseSjPhone the value for lose_found_tb.lose_sj_phone
     *
     * @mbg.generated Thu Apr 18 19:35:10 CST 2019
     */
    public void setLoseSjPhone(String loseSjPhone) {
        this.loseSjPhone = loseSjPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lose_found_tb.lose_man
     *
     * @return the value of lose_found_tb.lose_man
     *
     * @mbg.generated Thu Apr 18 19:35:10 CST 2019
     */
    public String getLoseMan() {
        return loseMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lose_found_tb.lose_man
     *
     * @param loseMan the value for lose_found_tb.lose_man
     *
     * @mbg.generated Thu Apr 18 19:35:10 CST 2019
     */
    public void setLoseMan(String loseMan) {
        this.loseMan = loseMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lose_found_tb.lose_phone
     *
     * @return the value of lose_found_tb.lose_phone
     *
     * @mbg.generated Thu Apr 18 19:35:10 CST 2019
     */
    public String getLosePhone() {
        return losePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lose_found_tb.lose_phone
     *
     * @param losePhone the value for lose_found_tb.lose_phone
     *
     * @mbg.generated Thu Apr 18 19:35:10 CST 2019
     */
    public void setLosePhone(String losePhone) {
        this.losePhone = losePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lose_found_tb.remarks
     *
     * @return the value of lose_found_tb.remarks
     *
     * @mbg.generated Thu Apr 18 19:35:10 CST 2019
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lose_found_tb.remarks
     *
     * @param remarks the value for lose_found_tb.remarks
     *
     * @mbg.generated Thu Apr 18 19:35:10 CST 2019
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

	public int getLoseState() {
		return loseState;
	}

	public void setLoseState(int loseState) {
		this.loseState = loseState;
	}
}