package com.csq.entity;

public class SchoolBus {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_bus_tb.id
     *
     * @mbg.generated Wed Jun 19 09:17:25 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_bus_tb.bus_driver
     *
     * @mbg.generated Wed Jun 19 09:17:25 CST 2019
     */
    private String busDriver;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_bus_tb.bus_number
     *
     * @mbg.generated Wed Jun 19 09:17:25 CST 2019
     */
    private String busNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_bus_tb.bus_come_time
     *
     * @mbg.generated Wed Jun 19 09:17:25 CST 2019
     */
    private String busComeTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_bus_tb.bus_address
     *
     * @mbg.generated Wed Jun 19 09:17:25 CST 2019
     */
    private String busAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_bus_tb.bus_stop_address
     *
     * @mbg.generated Wed Jun 19 09:17:25 CST 2019
     */
    private String busStopAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_bus_tb.bus_after
     *
     * @mbg.generated Wed Jun 19 09:17:25 CST 2019
     */
    private String busAfter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_bus_tb.bus_stop_time
     *
     * @mbg.generated Wed Jun 19 09:17:25 CST 2019
     */
    private String busStopTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_bus_tb.remark
     *
     * @mbg.generated Wed Jun 19 09:17:25 CST 2019
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_bus_tb.id
     *
     * @return the value of school_bus_tb.id
     *
     * @mbg.generated Wed Jun 19 09:17:25 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_bus_tb.id
     *
     * @param id the value for school_bus_tb.id
     *
     * @mbg.generated Wed Jun 19 09:17:25 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_bus_tb.bus_driver
     *
     * @return the value of school_bus_tb.bus_driver
     *
     * @mbg.generated Wed Jun 19 09:17:25 CST 2019
     */
    public String getBusDriver() {
        return busDriver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_bus_tb.bus_driver
     *
     * @param busDriver the value for school_bus_tb.bus_driver
     *
     * @mbg.generated Wed Jun 19 09:17:25 CST 2019
     */
    public void setBusDriver(String busDriver) {
        this.busDriver = busDriver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_bus_tb.bus_number
     *
     * @return the value of school_bus_tb.bus_number
     *
     * @mbg.generated Wed Jun 19 09:17:25 CST 2019
     */
    public String getBusNumber() {
        return busNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_bus_tb.bus_number
     *
     * @param busNumber the value for school_bus_tb.bus_number
     *
     * @mbg.generated Wed Jun 19 09:17:25 CST 2019
     */
    public void setBusNumber(String busNumber) {
        this.busNumber = busNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_bus_tb.bus_come_time
     *
     * @return the value of school_bus_tb.bus_come_time
     *
     * @mbg.generated Wed Jun 19 09:17:25 CST 2019
     */
    public String getBusComeTime() {
        return busComeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_bus_tb.bus_come_time
     *
     * @param busComeTime the value for school_bus_tb.bus_come_time
     *
     * @mbg.generated Wed Jun 19 09:17:25 CST 2019
     */
    public void setBusComeTime(String busComeTime) {
        this.busComeTime = busComeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_bus_tb.bus_address
     *
     * @return the value of school_bus_tb.bus_address
     *
     * @mbg.generated Wed Jun 19 09:17:25 CST 2019
     */
    public String getBusAddress() {
        return busAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_bus_tb.bus_address
     *
     * @param busAddress the value for school_bus_tb.bus_address
     *
     * @mbg.generated Wed Jun 19 09:17:25 CST 2019
     */
    public void setBusAddress(String busAddress) {
        this.busAddress = busAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_bus_tb.bus_stop_address
     *
     * @return the value of school_bus_tb.bus_stop_address
     *
     * @mbg.generated Wed Jun 19 09:17:25 CST 2019
     */
    public String getBusStopAddress() {
        return busStopAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_bus_tb.bus_stop_address
     *
     * @param busStopAddress the value for school_bus_tb.bus_stop_address
     *
     * @mbg.generated Wed Jun 19 09:17:25 CST 2019
     */
    public void setBusStopAddress(String busStopAddress) {
        this.busStopAddress = busStopAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_bus_tb.bus_after
     *
     * @return the value of school_bus_tb.bus_after
     *
     * @mbg.generated Wed Jun 19 09:17:25 CST 2019
     */
    public String getBusAfter() {
        return busAfter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_bus_tb.bus_after
     *
     * @param busAfter the value for school_bus_tb.bus_after
     *
     * @mbg.generated Wed Jun 19 09:17:25 CST 2019
     */
    public void setBusAfter(String busAfter) {
        this.busAfter = busAfter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_bus_tb.bus_stop_time
     *
     * @return the value of school_bus_tb.bus_stop_time
     *
     * @mbg.generated Wed Jun 19 09:17:25 CST 2019
     */
    public String getBusStopTime() {
        return busStopTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_bus_tb.bus_stop_time
     *
     * @param busStopTime the value for school_bus_tb.bus_stop_time
     *
     * @mbg.generated Wed Jun 19 09:17:25 CST 2019
     */
    public void setBusStopTime(String busStopTime) {
        this.busStopTime = busStopTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_bus_tb.remark
     *
     * @return the value of school_bus_tb.remark
     *
     * @mbg.generated Wed Jun 19 09:17:25 CST 2019
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_bus_tb.remark
     *
     * @param remark the value for school_bus_tb.remark
     *
     * @mbg.generated Wed Jun 19 09:17:25 CST 2019
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
}