server:
  servlet:
    context-path: /boot
  port: 8088

---
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_logistics?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: "Bozpower123#"
    
---

mybatis:
  type-aliases-package: com.csq.entity
  mapper-locations: classpath:mappers/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    